const data = {
  products: [
    {
      itemId: '11',
      itemCode: '11',
      itemDesc: 'Product - 11',
      itemGroup: 'Group-11',
      itemSupp: 'Supp-11',
      itemUnActv: '',
      itemUnit: '',
      itemTPRate: 11,
      itemMaxDesc: 11,
      itemSTax: '',
      itemLock: '',
    },
    {
      itemId: '12',
      itemCode: '',
      itemDesc: 'Product - 12',
      itemGroup: '',
      itemSupp: '',
      itemUnActv: '',
      itemUnit: '',
      itemTPRate: 22,
      itemMaxDesc: 22,
      itemSTax: '',
      itemLock: '',
    },
    {
      itemId: '13',
      itemCode: '',
      itemDesc: 'Product - 13',
      itemGroup: '',
      itemSupp: '',
      itemUnActv: '',
      itemUnit: '',
      itemTPRate: 33,
      itemMaxDesc: 33,
      itemSTax: '',
      itemLock: '',
    },
  ],
};

export default data;
